export const pokemonTypes = [
  'Normal', 
  'Fire', 
  'Water', 
  'Grass', 
  'Electric', 
  'Ice', 
  'Fighting', 
  'Poison', 
  'Ground', 
  'Flying', 
  'Psychic', 
  'Bug', 
  'Rock', 
  'Ghost', 
  'Dark', 
  'Dragon', 
  'Steel', 
  'Fairy', 
  ];
  
// export const yearsOfProduction = [
//   { title: "Year", value: "" },
//   { title: "2015", value: "2015" },
//   { title: "2016", value: "2016" },
//   { title: "2017", value: "2017" },
//   { title: "2018", value: "2018" },
//   { title: "2019", value: "2019" },
//   { title: "2020", value: "2020" },
//   { title: "2021", value: "2021" },
//   { title: "2022", value: "2022" },
//   { title: "2023", value: "2023" },
// ];

export const filterMountTypes = [
  {
    title: "Land",
    value: "Land",
  },
  {
    title: "Water",
    value: "Water",
  },
  {
    title: "Flying",
    value: "Flying",
  },
];

export const specificMountTypes: { [key: string]: string[] } = {
  'land': [
    'abomasnow', 
    'absol', 
    'aegislash', 
    'aggron', 
    'alakazam', 
    'amoonguss', 
    'arbok', 
    'arcanine', 
    'arctozolt', 
    'ariados', 
    'armaldo', 
    'audino', 
    'aurorus', 
    'bastiodon', 
    'bayleef', 
    'beartic', 
    'bewear', 
    'bisharp', 
    'blastoise', 
    'blaziken', 
    'blissey', 
    'boldore', 
    'boltund', 
    'bouffalant', 
    'breloom', 
    'bronzong', 
    'cacturne', 
    'camerupt', 
    'centiskorch', 
    'chansey', 
    'chesnaught', 
    'cinderace', 
    'clefable', 
    'coalossal', 
    'cobalion', 
    'conkeldurr', 
    'copperajah', 
    'crabominable', 
    'crustle', 
    'cryogonal', 
    'cufant', 
    'darmanitan', 
    'delphox', 
    'diggersby', 
    'dodrio', 
    'donphan', 
    'dracovish', 
    'dracozolt', 
    'drampa', 
    'drapion', 
    'druddigon', 
    'dubwool', 
    'duraludon', 
    'dusclops', 
    'dusknoir', 
    'eiscue', 
    'electrode', 
    'emboar', 
    'empoleon', 
    'entei', 
    'espeon', 
    'excadrill', 
    'exeggutor', 
    'exploud', 
    'falinks', 
    'feraligatr', 
    'ferrothorn', 
    'flareon', 
    'forretress', 
    'furfrou', 
    'gabite', 
    'galvantula', 
    'garbodor', 
    'gengar', 
    'gigalith', 
    'girafarig', 
    'glaceon', 
    'glalie', 
    'glastrier', 
    'gogoat', 
    'golduck', 
    'golem', 
    'goodra', 
    'granbull', 
    'graveler', 
    'greninja', 
    'groudon', 
    'gurdurr', 
    'guzzlord', 
    'hariyama', 
    'hatterene', 
    'haunter', 
    'haxorus', 
    'heatran', 
    'heracross', 
    'hippopotas', 
    'hippowdon', 
    'houndoom', 
    'incineroar', 
    'infernape', 
    'inteleon', 
    'jolteon', 
    'kangaskhan', 
    'keldeo', 
    'kommo-o', 
    'krookodile', 
    'kyurem', 
    'lairon', 
    'leafeon', 
    'lickilicky', 
    'lickitung', 
    'liepard', 
    'lucario', 
    'ludicolo', 
    'lurantis', 
    'luxray', 
    'lycanroc', 
    'machamp', 
    'machoke', 
    'mamoswine', 
    'manectric', 
    'meganium', 
    'melmetal', 
    'mienshao', 
    'morpeko', 
    'mudbray', 
    'mudsdale', 
    'muk', 
    'musharna', 
    'nidoking', 
    'nidoqueen', 
    'ninetales', 
    'numel', 
    'obstagoon', 
    'onix', 
    'oranguru', 
    'palossand', 
    'pangoro', 
    'parasect', 
    'passimian', 
    'persian', 
    'pheromosa', 
    'piloswine', 
    'pinsir', 
    'poliwrath', 
    'ponyta', 
    'probopass', 
    'purugly', 
    'pyroar', 
    'quagsire', 
    'quilava', 
    'raikou', 
    'rampardos', 
    'rapidash', 
    'raticate', 
    'regice', 
    'regidrago', 
    'regigigas', 
    'regirock', 
    'registeel', 
    'reuniclus', 
    'rhydon', 
    'rhyhorn', 
    'rhyperior', 
    'rillaboom', 
    'salazzle', 
    'samurott', 
    'sandaconda', 
    'sawk', 
    'sawsbuck', 
    'sceptile', 
    'scolipede', 
    'scyther', 
    'seismitoad', 
    'serperior', 
    'seviper', 
    'shelgon', 
    'shiftry', 
    'silvally', 
    'slaking', 
    'slowbro', 
    'slowking', 
    'snorlax', 
    'spectrier', 
    'stakataka', 
    'stantler', 
    'steelix', 
    'stonjourner', 
    'stoutland', 
    'suicune', 
    'swalot', 
    'sylveon', 
    'tangrowth', 
    'tauros', 
    'terrakion', 
    'thievul', 
    'throh', 
    'torkoal', 
    'torracat', 
    'torterra', 
    'trevenant', 
    'turtonator', 
    'type: null', 
    'typhlosion', 
    'tyranitar', 
    'tyrantrum', 
    'umbreon', 
    'ursaring', 
    'urshifu', 
    'vanilluxe', 
    'vaporeon', 
    'venusaur', 
    'victreebel', 
    'vileplume', 
    'virizion', 
    'weezing', 
    'wyrdeer', 
    'xerneas', 
    'xurkitree', 
    'zacian', 
    'zamazenta', 
    'zangoose', 
    'zarude', 
    'zebstrika', 
    'zeraora', 
    'zoroark', 
    'zweilous', 
    'zygarde', 
  ],
  'water': [
    'araquanid', 
    'arctovish', 
    'avalugg', 
    'barbaracle', 
    'barraskewda', 
    'bibarel', 
    'carracosta', 
    'clawitzer', 
    'cloyster', 
    'crawdaunt', 
    'dewgong', 
    'dragalge', 
    'drednaw', 
    'eelektross', 
    'floatzel', 
    'gastrodon', 
    'golisopod', 
    'gorebyss', 
    'grapploct', 
    'gyarados', 
    'huntail', 
    'jellicent', 
    'kabutops', 
    'kingdra', 
    'kyogre', 
    'lanturn', 
    'lapras', 
    'lumineon', 
    'malamar', 
    'mantine', 
    'milotic', 
    'nihilego', 
    'primarina', 
    'samurott', 
    'seaking', 
    'sealeo', 
    'sharpedo', 
    'starmie', 
    'swampert', 
    'tentacruel', 
    'wailmer', 
    'wailord', 
    'walrein', 
    'whiscash', 
  ],
  'flying': [
    'aerodactyl', 
    'altaria', 
    'arceus', 
    'archeops', 
    'articuno', 
    'braviary', 
    'buzzwole', 
    'celesteela', 
    'chandelure', 
    'charizard', 
    'chatot', 
    'claydol', 
    'corviknight', 
    'cramorant', 
    'cresselia', 
    'crobat', 
    'darkrai', 
    'decidueye', 
    'deoxys', 
    'dialga', 
    'dragapult', 
    'dragonite', 
    'drifblim', 
    'emolga', 
    'eternatus', 
    'fearow', 
    'flygon', 
    'frosmoth', 
    'garchomp', 
    'genesect', 
    'giratina', 
    'gliscor', 
    'golurk', 
    'ho-oh', 
    'honchkrow', 
    'hydreigon', 
    'klinklang', 
    'latias', 
    'latios', 
    'lugia', 
    'lunala', 
    'magnezone', 
    'mandibuzz', 
    'metagross', 
    'mewtwo', 
    'moltres', 
    'naganadel', 
    'necrozma', 
    'noctowl', 
    'noivern', 
    'orbeetle', 
    'palkia', 
    'pelipper', 
    'pidgeot', 
    'rayquaza', 
    'regieleki', 
    'reshiram', 
    'salamence', 
    'scizor', 
    'sigilyph', 
    'skarmory', 
    'solgaleo', 
    'staraptor', 
    'swanna', 
    'swellow', 
    'swoobat', 
    'talonflame', 
    'tapu bulu', 
    'tapu fini', 
    'tapu koko', 
    'tapu lele', 
    'togekiss', 
    'toucannon', 
    'tropius', 
    'unfezant', 
    'venomoth', 
    'vespiquen', 
    'vibrava', 
    'vikavolt', 
    'volcanion', 
    'volcarona', 
    'xatu', 
    'yanmega', 
    'yveltal', 
    'zapdos', 
    'zekrom', 
  ],
}

export const footerLinks = [
  {
    title: "About",
    links: [
      { title: "How it Works", url: "/" },
      { title: "Featured", url: "/" },
      { title: "Partnership", url: "/" },
      { title: "Business Relations", url: "/" },
    ],
  },
  {
    title: "Company",
    links: [
      { title: "Events", url: "/" },
      { title: "Blog", url: "/" },
      { title: "Podcast", url: "/" },
      { title: "Invite a Friend", url: "/" },
    ],
  },
  {
    title: "Socials",
    links: [
      { title: "Discord", url: "/" },
      { title: "Instagram", url: "/" },
      { title: "Twitter", url: "/" },
      { title: "Facebook", url: "/" },
    ],
  },
];